version: '3.5'

services:
    server:
        container_name: zoraddit_server
        build: ./server
        ports:
            - "4000:4000"
            - "8080:8080"
        environment:
            - NODE_ENV=development
        depends_on:
            - redis
            - postgres
        env_file:
            - ./server/.env
        networks: 
            - default
    web:
        container_name: zoraddit_web
        build: ./web
        ports:
            - "3000:3000"
            - "80:80"
        env_file:
            - ./web/.env.local
        depends_on:
            - server

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        expose: 
            - "6379"

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes: 
            - zoraddit:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PW}
            POSTGRES_DB: ${DATABASE_NAME}
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - default

volumes: 
    zoraddit:
networks:
    default: